### PR TITLE
Import exception from pylint.exceptions instead of utils

### PR DESCRIPTION
**Pull request by michael-k**
Also tries to use the newer name (already over three years old) first.

Fixes PyCQA/pylint-plugin-utils#15

### CODE REVIEW

**Comment by PCManticore** [comment]
Looks good here as well, but I wonder if we should still keep the current import form for compatibility with `pylint<2.4`

**Comment by paddycarey** [comment]
From a quick check it looks like `UnknownMessageError` has existed in `pylint.exceptions` since at least Pylint version 1.7.0 (https://github.com/PyCQA/pylint/blob/pylint-1.7.0/pylint/exceptions.py), so the import cleanup probably makes sense I think.

**Comment by michael-k** [comment]
Initially I decided against the cleanup to avoid any discussion in that direction in favor of a quick release.  I've pushed a second commit with the cleanup.  This should allow the maintainers to either include or exclude the cleanup with minimal effort.

**Comment by kdmccormick** [comment]
@PCManticore as @paddycarey noted, UnknownMessageError has existed in pylint.exceptions since since 1.7.0. It's been incidentally working for so long because pylint.utils used to import UnknownMessageError. In Pylint 2.4, pylint.utils was refactored to only expose particular functions.

**Comment by atodorov** [comment]
@carlio this broke pylint-django. Do you mind pushing a new version to PyPI. Maybe also add minimum version requirements in setup.py ?

**Comment by carlio** [comment]
@atodorov yes, will do this later - I'm on a train at the moment so will wait for reliable internet

**Comment by bittner** [comment]
Please note, everyone:

We would need more maintainers on this project. The [package on PyPI](https://pypi.org/project/pylint-plugin-utils/) only has a single maintainer. For a package that so many people seemingly depend on we must do better.

If Carl is on the train, on holiday, gone for months, \<your-reason-here\> this package becomes unusable for everyone. That's too risky. Pylint-django has 3 maintainers (the [pyroma](https://pypi.org/project/pyroma/) recommended minimum), this is already better. Pylint itself has 6.

How about adding the maintainers of pylint-django also as maintainers to this package? (Sorry, if that's a creepy suggestion.)

@carlio? @atodorov? @colinhowe? Or anyone else volunteering?

**Comment by atodorov** [comment]
@bittner +1 on my side, I can help maintai  this project too, also push builds to PyPI. All depending on time of course but so far I've managed ;-)

**Comment by carlio** [comment]
Version 0.6 is now on PyPI

@atodorov I am happy to add you as a maintainer if you want!

I think @colinhowe hasn't actually done much for pylint-django, not sure if he forgot about it :-)

**Comment by colinhowe** [comment]
Hello! Sorry, I've moved city and jobs in the past few months and haven't really had free time for anything apart from decorating the house :) I'm happy to be kept on the list and be a fallback reviewer if things get clogged up.

**Comment by lk-jeffpeck** [comment]
Can we get the latest `pylint-plugin-utils==0.6` on conda-forge?

**Pull request merged**
